### ISSUE TITLE
좋은 프로젝트 공유감사드립니다. : Yolo Visualizer 화면관련 질문

### ISSUE THREAD

**Issue by CPT-BJ** [JoSihun/MLAgentCameraAutoFlight#1]
안녕하세요. 올려주신 자료 덕분에 제가 진행중인 연구에 큰 도움이 될 것 같습니다.
저 역시 자율주행 드론을 가상환경에서 만들고 이를 현실로 옮기는 SIM2Real작업을 진행중에 있었습니다. 선생님의 프로젝트에서 특히 YOLOV4를 사용한 부분이 제 연구에도 큰 도움이 될 것 같습니다.

질문이 있어서 글을 남깁니다.

Yolo Visualizer 화면에 이미지 객체 인식을 위한 바운딩 박스가 생성이 되질 않는데,
혹시 이런경우 해결하셨던 방법을 알 수 있을까요?

아래 사진은 제가 해당 프로젝트를 플레이했을 때 화면입니다.

아마 <그림 2>에서 보이는 아래 메시지 때문인것 같습니다,
IndexOutOfRangeException: Invalid kernelIndex (19) passed, must be non-negative less than 24. 
<img width="921" alt="스크린샷 2022-03-31 오전 10 58 32" src="https://user-images.githubusercontent.com/101859950/160961188-0571d45c-1e2e-4824-9c70-2d05bf8f10ad.png">
<img width="919" alt="스크린샷 2022-03-31 오전 10 58 44" src="https://user-images.githubusercontent.com/101859950/160961211-3d4b0c67-37e5-4657-9b02-59f97c3e97e2.png">

**Comment by CPT-BJ** [comment]
아니면 제가 혹시 Visulaizer세팅을 잘못한걸까요?
<img width="287" alt="스크린샷 2022-03-31 오전 11 07 52" src="https://user-images.githubusercontent.com/101859950/160962003-30eaccbc-c610-4a61-8407-4d7470a87a17.png">

**Comment by CPT-BJ** [comment]
아 참고로 제가 지금 진행중인 프로젝트는 아래와 같습니다.
지금 막힌 부분이 딱 객체검출을 추가하는 부분인데, 이 프로젝트를 찾고 너무 기분이 좋았습니다.
*가능/불가능 여부도 몰랐기에

혹시 실례가 안된다면, 프로젝트를 작성하는 과정에서 참고하신 예제나, git 등 알 수 있겠습니까?
갑자기 이것저것 두서없이 물어봐서 죄송합니다.
https://www.facebook.com/groups/ReinforcementLearningKR/permalink/3054425008130052/

**Comment by ChoSihoon** [comment]
안녕하세요?
우선, 제 프로젝트에 깊은 관심을 갖고 연락 주신 부분에 감사드립니다.
 
우선 인스펙터 창만으로는 정확한 문제를 파악할 수 없을 것 같습니다.
하이어아키창과 현재 구성된 화면세팅을 모두 살펴봐야 정확히 알 수 있겠지만,
일단 첨부해주신 인스펙터창만 봤을 때는 큰 문제가 없어보입니다.
 
제시해주신 문제가 되는 부분에 대하여 주어진 정보가 너무 한정적입니다.
바운딩 박스가 보이지 않는다는 부분에 대하여, 여러가지 상황을 고려해 볼 수 있습니다.
 
1) 간단하게는 스크립트 오류로 실행 자체가 안 되는 상황
2) 실행은 되는데 바운딩 박스만 안 보이는 상황
3) 정상적인 실행이나 패키지가 정상적으로 import되지 않는 상황
4) 하이어아키 창의 오브젝트 명이 다르게 설정된 상황
5) 바운딩 박스가 보여야할 결과화면을 UI오브젝트가 아닌 일반 오브젝트로 연결한 상황
6) Visualizer에 연결된 input과 output이 제대로 연결되지 않은 상황
등등 '바운딩 박스가 보이지 않는' 한 가지 문제에 대해 여러 상황을 고려해 볼 수 있습니다.
 
지금은 오래되어 세세한 부분까지 잘 기억나지는 않지만,
제가 해당 프로젝트를 진행할 당시 YOLOv4-Tiny Barracuda 패키지를 import 할 때,
해당 패키지의 Visualizer Script를 뜯어 아래의 원리에 의거하여 일부 변경하여 문제해결을 시도해본 경우도 있습니다.
이렇듯 패키지를 그대로 사용하는 것 뿐만 아니라 원하는 용도에 맞게 일부 변경하여 사용하는 방법까지 
차근차근 고려해볼 수 있는 문제 상황을 먼저 모두 정리하신 후에,
하나씩 문제해결을 시도해보시는 것이 큰 도움이 될 것이라고 생각합니다.
 
'''
Unity YOLOv4-Tiny Barracuda의 기본적인 원리는 다음과 같다.
input으로 이미지를 넣고, output으로 input 이미지에 바운딩 박스의 여러 정보를 표현한 이미지를
Unity 오브젝트에 출력한다.
 
이를 실시간 라이브 카메라에 적용시키고자 한다면,
camera정보를 image로서 Visualizer에 input으로 사용하고,
output으로서 출력 될 화면을 'UI오브젝트'에 전달해야 될 것이다.
'''
 
말씀드린 답변이 진행하고 계시는 프로젝트에 큰 도움이 되길 바라며,
다시 한 번 제 프로젝트에 가져주신 큰 관심에 깊은 감사의 말씀드립니다.
 
-----Original Message-----
